"""
analyze_features.py — unified feature analysis for the atomic energy-level project.

Combines the two previous analysis scripts into one tool that runs for any element
or group of elements and produces a shareable report in three formats (PDF, XLSX,
HTML).

Two analysis modes:

  * Model-free (always)   — distributions, correlation matrix, mutual-information
    ranking per target, feature-range comparison, feature/target scatter and (for
    single-valence "alkali-like" atoms) Rydberg residuals, quantum-defect stability
    and n* distributions.
  * Model-based (optional)— permutation feature importance for a trained MLP. Runs
    only when a checkpoint is supplied or auto-found; skipped gracefully otherwise.

Input is auto-detected per element:

  * rich xlsx  ``data/<El>_features_rich_<source>.xlsx`` (output of
    preprocess_atomic.py) when present — columns are read directly, no recomputation.
  * legacy CSV ``data/<El>_features.csv`` otherwise — valence/Rydberg/derived
    features are computed on the fly (the alkali path).

Per-element constants (ionization energy, Z, A …) come from config_preprocess.yaml.

Usage::

    python preprocess/analyze_features.py --elements Li Na K Rb Cs Fr
    python preprocess/analyze_features.py --elements Co
    python preprocess/analyze_features.py --elements Co --checkpoint saved_models/<model>.pt
    python preprocess/analyze_features.py --config config_preprocess.yaml --source nist --elements K

Author: Aga (unified with Claude Code)
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import sys
import warnings

warnings.filterwarnings("ignore")

# Console output contains unicode (→, cm⁻¹, ★); make stdout/stderr UTF-8 so it does
# not crash on Windows' default cp1252 code page.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

import numpy as np
import pandas as pd
import yaml
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

from sklearn.feature_selection import mutual_info_regression
from sklearn.preprocessing import StandardScaler

# Make the project root importable so we can (optionally) reuse FEATURE_GROUPS.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_THIS_DIR)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

R_INF = 109737.316   # Rydberg constant, cm^-1

# Canonical column names every loader maps onto, so the plotting/report code is
# source-agnostic.
LEVEL_COL = "Level (cm-1)"     # raw experimental energy (the headline target)

L_NAMES = {0: "s", 1: "p", 2: "d", 3: "f", 4: "g", 5: "h"}
L_COLORS = ["#1D9E75", "#378ADD", "#BA7517", "#D4537E", "#7F77DD", "#888780"]

# Stable colours for the alkali atoms; any other element is assigned from a palette.
ELEMENT_COLORS = {
    "Li": "#E24B4A", "Na": "#BA7517", "K": "#1D9E75",
    "Rb": "#378ADD", "Cs": "#7F77DD", "Fr": "#D4537E",
}
_PALETTE = ["#8B5CF6", "#0EA5E9", "#22C55E", "#F59E0B", "#EF4444", "#14B8A6",
            "#6366F1", "#EC4899", "#84CC16", "#F97316"]

# Canonical model-free feature set shared by every input source.
# NOTE: val_ei_n / val_ei_l columns are added dynamically in select_features()
# based on the per-element max_valence from config_preprocess.yaml, so that
# transition metals (e.g. Co, max_valence=9) get all 9 (n, l) pairs while
# alkali metals (max_valence=1) get only the single outer-electron pair.
_BASE_FEATURES_FIXED = ["J"]          # always included (valence slots added dynamically)
_QUANTUM_FEATURES    = ["S_qn", "L_qn"]
_ATOMIC_FEATURES     = ["Z", "A"]
_RYDBERG_FEATURES    = ["n_star", "rydberg_pred", "one_over_nstar_sq"]
_DERIVED_FEATURES    = ["total_electrons", "max_principal_n", "valence_electrons",
                         "core_electrons", "unpaired_electrons"]

# Extra transition-metal physics features, only added when every element comes
# from a rich xlsx. Mirrors the relevant groups in AtomicDataset.FEATURE_GROUPS.
_RICH_PHYSICS_FALLBACK = ["J_sq", "L_sq", "S_sq", "lande_so_term",
                           "n_3d", "d_holes", "d_from_half", "is_half_filled",
                           "Z_eff", "Z_eff_sq", "E_so_estimate"]

# Parity and subterm decomposition columns — only present in rich xlsx files
# (generated by preprocess_atomic.py). These encode information about whether the
# NIST term is a pure LS state or a mixture of several components, which the
# model uses when add_transition_metal_features=True.
_RICH_SUBTERM_FEATURES = [
    "parity_computed",                  # 0/1 parity flag computed from orbital occupancy
    "term_known",                       # 1 if NIST assigned S_qn (confirmed LS term)
    "comp1_S", "comp1_L",              # leading-component (S, L) quantum numbers
    "comp2_S", "comp2_L",              # second-component (S, L)
    "comp3_S", "comp3_L",              # third-component  (S, L)
    "subres_S", "subres_L",            # sub-resultant (S, L) from all components
    "n_components", "has_subresultant", # number of LS components; flag for sub-resultant
]

# Candidate targets, in display order. Only those present (with data) are used.
_TARGET_CANDIDATES = [
    ("log_binding_energy",     "log_binding_energy"),
    (LEVEL_COL,                f"raw_energy ({LEVEL_COL})"),
    ("binding_energy",         "binding_energy"),
    ("inverse_binding_energy", "inverse_binding_energy"),
]


def ensure_element_colors(elements):
    """Assign a stable colour to every element (keeps the known alkali colours)."""
    i = 0
    for el in elements:
        if el not in ELEMENT_COLORS:
            ELEMENT_COLORS[el] = _PALETTE[i % len(_PALETTE)]
            i += 1


def get_rich_physics_features():
    """
    Return the transition-metal physics feature columns, reusing
    AtomicDataset.FEATURE_GROUPS when importable (it pulls in torch) and falling
    back to a local list otherwise so the model-free path never needs torch.
    """
    try:
        from AtomicDataset import FEATURE_GROUPS
        cols = []
        for group in ("angular_momentum", "d_electron", "screening", "spin_orbit"):
            cols.extend(FEATURE_GROUPS.get(group, []))
        return cols
    except Exception:
        return list(_RICH_PHYSICS_FALLBACK)


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_preprocess_config(config_path):
    """
    Read config_preprocess.yaml (the run manifest) and return (settings, element_info).

    settings: {source, data_dir, report_dir, constants_file}
    element_info: {symbol: {symbol, species, Z, A, ionization_energy, max_valence, ...}}

    Per-element physical constants come from the master table (element_data),
    looked up by each entry's species/symbol; the yaml only says which species to
    analyse and where their raw inputs live. Inline entry values still override.
    """
    if not os.path.exists(config_path):
        sys.exit(f"ERROR: config not found: {config_path}")
    with open(config_path, "r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh) or {}

    settings = {
        "source": (cfg.get("source") or "kurucz").lower(),
        "data_dir": cfg.get("data_dir", "data"),
        "report_dir": cfg.get("report_dir", os.path.join("preprocess", "reports")),
        "constants_file": cfg.get("constants_file"),
    }
    constants_file = settings["constants_file"]

    element_info = {}
    for entry in (cfg.get("elements") or []):
        e = dict(entry or {})
        species_key = e.get("species") or e.get("symbol") or e.get("element")
        if not species_key:
            continue
        try:
            from element_data import get_species_constants, normalize_species
            c = (get_species_constants(species_key, constants_file) if constants_file
                 else get_species_constants(species_key))
            merged = {
                "symbol": c.get("symbol"),
                "species": normalize_species(species_key),
                "Z": c.get("Z"), "A": c.get("A"),
                "ionization_energy": c.get("ionization_energy_cm-1"),
                "max_valence": c.get("max_valence"),
                "zeta_3d": c.get("zeta_3d"),
            }
            merged.update(e)          # inline entry values override the table
            e = merged
        except Exception as exc:
            print(f"  ⚠ constants lookup failed for '{species_key}' "
                  f"({type(exc).__name__}); using inline values only.")
        sym = e.get("symbol") or e.get("element") or str(species_key).split()[0]
        element_info[sym] = e
    return settings, element_info


def parse_args():
    p = argparse.ArgumentParser(description="Unified feature analysis for atomic energy-level data")
    p.add_argument("--config", default=os.path.join(_ROOT, "config_preprocess.yaml"),
                   help="Path to config_preprocess.yaml (per-element constants)")
    p.add_argument("--elements", nargs="+", default=None,
                   help="Element symbols to analyse (default: all in the config)")
    p.add_argument("--source", default=None,
                   help="Rich-xlsx source suffix to prefer (nist/kurucz). Default: config 'source'.")
    p.add_argument("--data-dir", default=None,
                   help="Directory holding the feature files (default: config 'data_dir')")
    p.add_argument("--out", default=None,
                   help="Output base path WITHOUT extension "
                        "(default: <report_dir>/features_<elements>_<source>)")
    p.add_argument("--formats", default="pdf,xlsx,html",
                   help="Comma-separated subset of pdf,xlsx,html (default: all)")
    p.add_argument("--no-rydberg", action="store_true",
                   help="Skip Rydberg-specific diagnostic pages")
    # Model-based (permutation importance) options
    p.add_argument("--checkpoint", default=None,
                   help="Trained .pt checkpoint → enables permutation importance")
    p.add_argument("--training-config", default=os.path.join(_ROOT, "config_atomic.yaml"),
                   help="Training config used to rebuild the dataset/model for permutation importance")
    p.add_argument("--no-permutation", action="store_true",
                   help="Never run permutation importance, even if a checkpoint is found")
    return p.parse_args()


# ---------------------------------------------------------------------------
# CSV-path feature computation (legacy {El}_features.csv → canonical columns)
# ---------------------------------------------------------------------------

def add_valence_encoding(df: pd.DataFrame, max_valence: int = 1) -> pd.DataFrame:
    """
    Minimal valence encoding matching AtomicDataset logic: sort electrons by the
    Madelung rule, keep the outermost ``max_valence``, pad at the front.
    """
    import re
    orbital_pattern = re.compile(r"^(\d+)([spdfgh])$")
    orbital_cols = [c for c in df.columns if orbital_pattern.match(c)]

    def orbital_order(col):
        m = orbital_pattern.match(col)
        n, l_let = int(m.group(1)), m.group(2)
        l = {"s": 0, "p": 1, "d": 2, "f": 3, "g": 4, "h": 5}[l_let]
        return (n + l, n, l)

    orbital_cols_sorted = sorted(orbital_cols, key=orbital_order)

    feature_cols = []
    for i in range(max_valence):
        feature_cols.extend([f"val_e{i + 1}_n", f"val_e{i + 1}_l"])

    rows = []
    for _, row in df.iterrows():
        electrons = []
        for col in orbital_cols_sorted:
            val = row[col]
            if pd.isna(val) or int(val) == 0:
                continue
            m = orbital_pattern.match(col)
            n, l_let = int(m.group(1)), m.group(2)
            l = {"s": 0, "p": 1, "d": 2, "f": 3, "g": 4, "h": 5}[l_let]
            electrons.extend([(n, l)] * int(val))

        valence = electrons[-max_valence:] if len(electrons) >= max_valence else electrons
        while len(valence) < max_valence:
            valence.insert(0, (0, 0))

        flat = []
        for (n, l) in valence:
            flat.extend([n, l])
        rows.append(flat)

    enc = pd.DataFrame(rows, columns=feature_cols, index=df.index)
    return pd.concat([df, enc], axis=1)


def add_rydberg_features(df: pd.DataFrame, level_col: str, ie_map: dict) -> pd.DataFrame:
    """
    Compute the quantum defect (delta), then per-(element, l) mean defect, and
    derive n_star / rydberg_pred / one_over_nstar_sq / binding_energy.

    ie_map: {element_symbol: ionization_energy_cm-1}. Elements absent from the map
    get NaN Rydberg features (they are not single-valence Rydberg series).
    """
    alkali = set(ie_map.keys())
    max_ev = sum(1 for c in df.columns if c.startswith("val_e") and c.endswith("_n"))
    n_cols = [f"val_e{i + 1}_n" for i in range(max_ev)]
    l_cols = [f"val_e{i + 1}_l" for i in range(max_ev)]

    def outer_electron(row):
        for nc, lc in zip(reversed(n_cols), reversed(l_cols)):
            n = row.get(nc, 0)
            if pd.notna(n) and int(n) > 0:
                return int(n), int(row[lc])
        return None, None

    df = df.copy()

    # Step 1: quantum defect per row.
    defects = []
    for _, row in df.iterrows():
        el = row["Element"]
        if el not in alkali:
            defects.append(np.nan)
            continue
        n, _l = outer_electron(row)
        if n is None:
            defects.append(np.nan)
            continue
        binding = ie_map[el] - float(row[level_col])
        if binding <= 0:
            defects.append(np.nan)
            continue
        n_star_val = np.sqrt(R_INF / binding)
        defects.append(n - n_star_val)
    df["quantum_defect"] = defects

    # Step 2: mean defect per (element, l) — proxy for the series-level defect.
    delta_map = (
        df.groupby(["Element", "val_e1_l"])["quantum_defect"].mean().to_dict()
    )

    # Step 3: apply.
    n_stars, ryd_preds, one_over = [], [], []
    for _, row in df.iterrows():
        el = row["Element"]
        if el not in alkali:
            n_stars.append(np.nan); ryd_preds.append(np.nan); one_over.append(np.nan)
            continue
        n, l = outer_electron(row)
        if n is None:
            n_stars.append(np.nan); ryd_preds.append(np.nan); one_over.append(np.nan)
            continue
        delta = delta_map.get((el, l), 0.0)
        n_eff = n - delta
        if n_eff <= 0:
            n_stars.append(np.nan); ryd_preds.append(np.nan); one_over.append(np.nan)
            continue
        n_stars.append(n_eff)
        ryd_preds.append(ie_map[el] - R_INF / n_eff ** 2)
        one_over.append(1.0 / n_eff ** 2)

    df["n_star"] = n_stars
    df["rydberg_pred"] = ryd_preds
    df["one_over_nstar_sq"] = one_over
    df["binding_energy"] = df["Element"].map(ie_map).astype(float) - df[level_col]
    return df


def add_derived_features(df: pd.DataFrame) -> pd.DataFrame:
    """Total / valence / core electron counts and max principal n from orbital columns."""
    import re
    orbital_pattern = re.compile(r"^(\d+)([spdfgh])$")
    orbital_cols = [c for c in df.columns if orbital_pattern.match(c)]

    df = df.copy()
    total_electrons, max_principal_ns, valence_electrons_list = [], [], []

    for _, row in df.iterrows():
        total, max_n = 0, 0
        for col in orbital_cols:
            val = row.get(col, 0)
            if pd.isna(val):
                continue
            count = int(val)
            if count > 0:
                n = int(orbital_pattern.match(col).group(1))
                total += count
                max_n = max(max_n, n)
        total_electrons.append(total)
        max_principal_ns.append(max_n)

        valence = 0
        for col in orbital_cols:
            val = row.get(col, 0)
            if pd.isna(val):
                continue
            count = int(val)
            if count > 0 and int(orbital_pattern.match(col).group(1)) == max_n:
                valence += count
        valence_electrons_list.append(valence)

    df["total_electrons"] = total_electrons
    df["max_principal_n"] = max_principal_ns
    df["valence_electrons"] = valence_electrons_list
    df["core_electrons"] = df["total_electrons"] - df["valence_electrons"]
    if "S_qn" in df.columns:
        df["unpaired_electrons"] = (2 * df["S_qn"]).round().astype(int)
    else:
        df["unpaired_electrons"] = 0
    return df


# ---------------------------------------------------------------------------
# Loaders (auto-detect rich xlsx vs legacy CSV) → canonical schema
# ---------------------------------------------------------------------------

def rich_xlsx_path(element, data_dir, source):
    return os.path.join(data_dir, f"{element}_features_rich_{source}.xlsx")


def csv_path(element, data_dir):
    return os.path.join(data_dir, f"{element}_features.csv")


# rich column -> canonical column
_RICH_RENAME = {
    "OBS.LEVEL": LEVEL_COL,
    "result_S": "S_qn",
    "result_L": "L_qn",
    "rydberg_prediction": "rydberg_pred",
    "Binding_Energy_cm-1": "binding_energy",
    "Log_Binding_Energy_cm-1": "log_binding_energy",
    "Inverse_Binding_Energy_cm-1": "inverse_binding_energy",
}


def load_rich_element(element, data_dir, source) -> pd.DataFrame:
    """Load a rich xlsx and map it onto the canonical schema (no recomputation)."""
    path = rich_xlsx_path(element, data_dir, source)
    df = pd.read_excel(path, sheet_name="features")
    df["Element"] = element
    for src, dst in _RICH_RENAME.items():
        if src in df.columns and dst not in df.columns:
            df = df.rename(columns={src: dst})
    # Columns the rich file does not carry but the canonical schema expects.
    if "quantum_defect" not in df.columns:
        df["quantum_defect"] = np.nan
    if "unpaired_electrons" not in df.columns:
        df["unpaired_electrons"] = (2 * df["S_qn"]).round().astype(int) \
            if "S_qn" in df.columns else 0
    return df


def load_csv_element(element, data_dir, ionization_energy) -> pd.DataFrame:
    """Load a legacy {El}_features.csv and compute the canonical features."""
    path = csv_path(element, data_dir)
    df = pd.read_csv(path)
    df["Element"] = element
    if LEVEL_COL not in df.columns:
        sys.exit(f"ERROR: column '{LEVEL_COL}' not in {path}. Available: {df.columns.tolist()}")
    df = add_valence_encoding(df, max_valence=1)
    df = add_rydberg_features(df, LEVEL_COL, {element: ionization_energy})
    df["log_binding_energy"] = np.log(df["binding_energy"].clip(lower=1e-6))
    df["inverse_binding_energy"] = 1.0 / df["binding_energy"].replace(0, np.nan)
    df = add_derived_features(df)
    return df


def load_elements(elements, data_dir, source, element_info):
    """
    Auto-detect and load every element into one canonical DataFrame.

    Returns (df, modes) where modes maps element → 'rich' | 'csv'.
    """
    frames, modes = [], {}
    for el in elements:
        rpath = rich_xlsx_path(el, data_dir, source)
        cpath = csv_path(el, data_dir)
        if os.path.exists(rpath):
            d = load_rich_element(el, data_dir, source)
            modes[el] = "rich"
            src_desc = os.path.basename(rpath)
        elif os.path.exists(cpath):
            ie = (element_info.get(el) or {}).get("ionization_energy")
            if ie is None:
                sys.exit(f"ERROR: {el} has no rich xlsx and no ionization_energy in config "
                         f"(needed to compute Rydberg features from {cpath}).")
            d = load_csv_element(el, data_dir, float(ie))
            modes[el] = "csv"
            src_desc = os.path.basename(cpath)
        else:
            sys.exit(f"ERROR: no feature file for {el}: tried {rpath} and {cpath}")
        lo = d[LEVEL_COL].min()
        hi = d[LEVEL_COL].max()
        print(f"  {el:<3} [{modes[el]:<4}] {len(d):>4} samples  "
              f"level {lo:.0f}-{hi:.0f} cm^-1  ({src_desc})")
        frames.append(d)

    df = pd.concat(frames, ignore_index=True)
    return df, modes


# ---------------------------------------------------------------------------
# Feature / target selection
# ---------------------------------------------------------------------------

def _build_valence_features(df, modes, element_info):
    """
    Return the list of val_ei_n / val_ei_l columns to include in analysis.

    The number of slots equals the maximum max_valence across the elements being
    analysed (read from element_info / config_preprocess.yaml).  For transition
    metals like Co (max_valence=9) this yields 18 features (9 n/l pairs); for
    alkali metals (max_valence=1) it yields the single outer-electron pair.

    Including all slots — not just slot 1 — lets the analysis *reveal* which
    slots matter for each element (e.g. for Co: slots 1, 8, 9 are the physically
    active ones for the 3d-4s configuration space).
    """
    elements_in_run = list(modes.keys()) if modes else list(df["Element"].unique())

    if element_info:
        max_val = max(
            (int((element_info.get(el) or {}).get("max_valence", 1))
             for el in elements_in_run),
            default=1,
        )
    else:
        # Fallback: detect from column names already present in df
        slot_nums = [
            int(c.split("_e")[1].split("_")[0])
            for c in df.columns
            if c.startswith("val_e") and c.endswith("_n")
        ]
        max_val = max(slot_nums, default=1)

    feats = []
    for i in range(1, max_val + 1):
        feats.extend([f"val_e{i}_n", f"val_e{i}_l"])
    return feats


def select_features(df, modes, element_info=None):
    """
    Pick the canonical features present in df with real variance.

    Feature groups included (in order):
      - val_ei_n / val_ei_l for i in 1..max_valence  (dynamic, per config_preprocess.yaml)
      - J (total angular momentum, always)
      - S_qn, L_qn (quantum numbers)
      - Z, A (atomic properties, skipped when constant = single-element dataset)
      - n_star, rydberg_pred, one_over_nstar_sq (Rydberg, when available)
      - total_electrons, max_principal_n, valence_electrons, core_electrons, unpaired_electrons

    Rich-mode extras (only when every element comes from a rich xlsx):
      - transition-metal physics: J_sq, L_sq, S_sq, lande_so_term, n_3d, d_holes, …
      - parity and subterm decomposition: parity_computed, term_known, comp*_S/L, …
    """
    valence_feats = _build_valence_features(df, modes, element_info)

    feats = valence_feats + list(_BASE_FEATURES_FIXED)
    for group in (_QUANTUM_FEATURES, _ATOMIC_FEATURES, _RYDBERG_FEATURES, _DERIVED_FEATURES):
        feats.extend(group)

    if modes and all(m == "rich" for m in modes.values()):
        feats.extend(get_rich_physics_features())   # angular-momentum, d-electron, screening, SO
        feats.extend(_RICH_SUBTERM_FEATURES)         # parity, term_known, subterm components

    # Deduplicate (preserve order), keep only columns present with >1 distinct non-null value.
    seen, out = set(), []
    for f in feats:
        if f in seen or f not in df.columns:
            continue
        seen.add(f)
        if df[f].dropna().nunique() > 1:
            out.append(f)
    return out


def get_targets(df):
    """Return (col, label) target tuples that exist with usable data."""
    out = []
    for col, label in _TARGET_CANDIDATES:
        if col in df.columns and df[col].dropna().nunique() > 1:
            out.append((col, label))
    return out


def compute_mi_table(df, features, targets):
    """Return {label: DataFrame[feature, mutual_information]} sorted descending."""
    results = {}
    for col, label in targets:
        avail = [f for f in features if f in df.columns and f != col]
        if not avail:
            continue
        target_vals = df[col].dropna()
        common = df[avail].dropna().index.intersection(target_vals.index)
        if len(common) < 3:
            continue
        X = StandardScaler().fit_transform(df.loc[common, avail].values)
        y = df.loc[common, col].values
        mi = mutual_info_regression(X, y, random_state=42)
        results[label] = (
            pd.DataFrame({"feature": avail, "mutual_information": mi})
            .sort_values("mutual_information", ascending=False)
            .reset_index(drop=True)
        )
    return results


def build_summary_table(df, features):
    """Per-feature descriptive stats over the combined dataset."""
    rows = []
    for f in features:
        s = pd.to_numeric(df[f], errors="coerce").dropna()
        rows.append({
            "feature": f,
            "count": int(s.shape[0]),
            "n_unique": int(s.nunique()),
            "mean": s.mean(), "std": s.std(),
            "min": s.min(), "max": s.max(),
        })
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Plotting helpers
# ---------------------------------------------------------------------------

def _suptitle(fig, text):
    fig.suptitle(text, fontsize=13, fontweight="bold", y=1.01)


def _legend_elements(elements):
    from matplotlib.patches import Patch
    return [Patch(facecolor=ELEMENT_COLORS.get(e, "gray"), label=e) for e in elements]


def plot_feature_distributions(df, features, elements, pdf):
    n = len(features)
    ncols = 4
    nrows = (n + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(14, 3 * nrows))
    axes = np.array(axes).flatten()
    i = -1
    for i, feat in enumerate(features):
        ax = axes[i]
        for el in elements:
            sub = df[df["Element"] == el][feat].dropna()
            if sub.empty:
                continue
            ax.hist(sub, bins=20, color=ELEMENT_COLORS.get(el, "gray"),
                    label=el, alpha=0.6, edgecolor="none", density=True)
        ax.set_title(feat, fontsize=10)
        ax.set_xlabel("value", fontsize=8)
        ax.set_ylabel("density", fontsize=8)
        ax.tick_params(labelsize=7)
    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)
    if len(elements) > 1:
        fig.legend(handles=_legend_elements(elements), loc="upper right", fontsize=9, title="Element")
    _suptitle(fig, "Feature distributions (by element)")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_correlation_matrix(df, features, targets, pdf):
    target_cols = [c for c, _ in targets]
    all_cols = list(features) + [t for t in target_cols if t not in features]
    available = [f for f in all_cols if f in df.columns]
    corr = df[available].corr()
    n = len(available)
    n_feat = len([f for f in features if f in df.columns])

    fig, ax = plt.subplots(figsize=(max(8, n * 0.75), max(6, n * 0.72)))
    im = ax.imshow(corr.values, cmap="RdBu_r", vmin=-1, vmax=1, aspect="auto")
    plt.colorbar(im, ax=ax, fraction=0.03)
    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    labels = [f"★ {c}" if c in target_cols else c for c in available]
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=9)
    ax.set_yticklabels(labels, fontsize=9)
    for i in range(n):
        for j in range(n):
            v = corr.values[i, j]
            if abs(v) > 0.25:
                ax.text(j, i, f"{v:.2f}", ha="center", va="center",
                        fontsize=7, color="white" if abs(v) > 0.7 else "black")
    if target_cols:
        sep = n_feat - 0.5
        ax.axhline(sep, color="white", lw=2)
        ax.axvline(sep, color="white", lw=2)
    _suptitle(fig, "Feature correlation matrix  (★ = target variables)\n"
                   "|r|>0.8 suggests redundancy")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_mutual_information(mi_results, pdf):
    if not mi_results:
        return
    n_targets = len(mi_results)
    ncols = 2
    nrows = (n_targets + ncols - 1) // ncols
    n_feat = max(len(res) for res in mi_results.values())
    subplot_h = max(4, n_feat * 0.38)
    fig, axes = plt.subplots(nrows, ncols, figsize=(18, subplot_h * nrows))
    axes = np.array(axes).flatten()
    for i, (label, res) in enumerate(mi_results.items()):
        ax = axes[i]
        feats = res["feature"].tolist()
        mi = res["mutual_information"].values
        median_mi = np.median(mi)
        colors = ["#1D9E75" if v > median_mi else "#888780" for v in mi]
        bars = ax.barh(feats[::-1], mi[::-1], color=colors[::-1], height=0.6)
        ax.set_xlabel("Mutual information", fontsize=9)
        ax.axvline(median_mi, color="#BA7517", ls="--", lw=1, label="median")
        ax.legend(fontsize=8)
        ax.set_title(f"target: {label}", fontsize=10, fontweight="bold")
        ax.tick_params(labelsize=7)
        x_pad = max(mi) * 0.01 if max(mi) > 0 else 0.001
        for bar, val in zip(bars, mi[::-1]):
            ax.text(val + x_pad, bar.get_y() + bar.get_height() / 2,
                    f"{val:.3f}", va="center", fontsize=7)
    for j in range(n_targets, len(axes)):
        axes[j].set_visible(False)
    _suptitle(fig, "Mutual information ranking — feature importance per target\n"
                   "(higher = more informative; near-zero = essentially noise for that target)")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_feature_target_scatter(df, features, target, elements, pdf):
    n = len(features)
    ncols = 3
    nrows = (n + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(14, 3.5 * nrows))
    axes = np.array(axes).flatten()
    i = -1
    for i, feat in enumerate(features):
        ax = axes[i]
        for el in elements:
            sub = df[df["Element"] == el][[feat, target]].dropna()
            if sub.empty:
                continue
            ax.scatter(sub[feat], sub[target], s=12, alpha=0.5,
                       color=ELEMENT_COLORS.get(el, "gray"), label=el)
        ax.set_xlabel(feat, fontsize=8)
        ax.set_ylabel(target, fontsize=8)
        ax.set_title(f"{feat} vs {target}", fontsize=9)
        ax.tick_params(labelsize=7)
    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)
    if len(elements) > 1:
        fig.legend(handles=_legend_elements(elements), loc="upper right", fontsize=9, title="Element")
    _suptitle(fig, f"Feature vs target ({target}) scatter plots")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_rydberg_residuals(df, elements, pdf):
    if "rydberg_pred" not in df.columns or "n_star" not in df.columns:
        return
    df = df.copy()
    df["rydberg_residual"] = df[LEVEL_COL] - df["rydberg_pred"]
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    ax = axes[0]
    for l_val in sorted(df["val_e1_l"].dropna().unique()):
        sub = df[df["val_e1_l"] == l_val][["n_star", "rydberg_residual"]].dropna()
        if sub.empty:
            continue
        ax.scatter(sub["n_star"], sub["rydberg_residual"], s=15, alpha=0.6,
                   color=L_COLORS[int(l_val) % len(L_COLORS)],
                   label=L_NAMES.get(int(l_val), str(int(l_val))))
    ax.axhline(0, color="black", lw=0.8, ls="--")
    ax.set_xlabel("n* (effective quantum number)", fontsize=10)
    ax.set_ylabel("Residual: true − Rydberg prediction (cm⁻¹)", fontsize=10)
    ax.set_title("Rydberg residuals vs n*", fontsize=11)
    ax.legend(title="l", fontsize=9, title_fontsize=9)
    ax.tick_params(labelsize=8)
    ax = axes[1]
    for el in elements:
        sub = df[df["Element"] == el][["n_star", "rydberg_residual"]].dropna()
        if sub.empty:
            continue
        ax.scatter(sub["n_star"], sub["rydberg_residual"], s=15, alpha=0.6,
                   color=ELEMENT_COLORS.get(el, "gray"), label=el)
    ax.axhline(0, color="black", lw=0.8, ls="--")
    ax.set_xlabel("n* (effective quantum number)", fontsize=10)
    ax.set_ylabel("Residual (cm⁻¹)", fontsize=10)
    ax.set_title("Rydberg residuals by element", fontsize=11)
    ax.legend(title="Element", fontsize=9)
    ax.tick_params(labelsize=8)
    _suptitle(fig, "Rydberg residuals (true level − Rydberg prediction)")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_quantum_defect(df, elements, pdf):
    if "quantum_defect" not in df.columns or df["quantum_defect"].dropna().empty:
        return
    unique_ls = sorted(df["val_e1_l"].dropna().unique())
    if not unique_ls:
        return
    ncols = min(len(unique_ls), 3)
    nrows = (len(unique_ls) + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 4 * nrows))
    axes = np.array(axes).flatten()
    i = -1
    for i, l_val in enumerate(unique_ls):
        ax = axes[i]
        for el in elements:
            sub = df[(df["Element"] == el) & (df["val_e1_l"] == l_val)][
                ["val_e1_n", "quantum_defect"]].dropna()
            if sub.empty:
                continue
            sub = sub.sort_values("val_e1_n")
            ax.plot(sub["val_e1_n"], sub["quantum_defect"], "o-",
                    color=ELEMENT_COLORS.get(el, "gray"), ms=5, alpha=0.8, label=el)
        ax.set_title(f"l={int(l_val)} ({L_NAMES.get(int(l_val), '?')})", fontsize=10)
        ax.set_xlabel("n (principal quantum number)", fontsize=9)
        ax.set_ylabel("δ = n − n*", fontsize=9)
        ax.tick_params(labelsize=8)
        mean_delta = df[df["val_e1_l"] == l_val]["quantum_defect"].mean()
        if not np.isnan(mean_delta):
            ax.axhline(mean_delta, color="gray", ls="--", lw=0.8, label=f"mean δ={mean_delta:.3f}")
        ax.legend(fontsize=8)
    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)
    _suptitle(fig, "Quantum defect δ = n − n* per angular-momentum series\n"
                   "Ideally a flat horizontal line")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_feature_ranges(df, features, elements, pdf):
    available = [f for f in features if f in df.columns]
    n = len(available)
    if n == 0:
        return
    fig, axes = plt.subplots(1, n, figsize=(max(10, 2 * n), 5))
    if n == 1:
        axes = [axes]
    for i, feat in enumerate(available):
        ax = axes[i]
        data_by_el, labels = [], []
        for el in elements:
            sub = df[df["Element"] == el][feat].dropna()
            if not sub.empty:
                data_by_el.append(sub.values)
                labels.append(el)
        if not data_by_el:
            ax.set_visible(False)
            continue
        parts = ax.violinplot(data_by_el, showmedians=True, showextrema=True)
        for j, pc in enumerate(parts["bodies"]):
            pc.set_facecolor(ELEMENT_COLORS.get(labels[j], "gray"))
            pc.set_alpha(0.7)
        ax.set_xticks(range(1, len(labels) + 1))
        ax.set_xticklabels(labels, fontsize=9)
        ax.set_title(feat, fontsize=10)
        ax.set_ylabel("value", fontsize=8)
        ax.tick_params(labelsize=7)
    _suptitle(fig, "Feature value ranges per element (violin plots)")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_nstar_distribution(df, elements, pdf):
    if "n_star" not in df.columns or df["n_star"].dropna().empty:
        return
    fig, axes = plt.subplots(1, len(elements), figsize=(5 * len(elements), 4), squeeze=False)
    axes = axes[0]
    for i, el in enumerate(elements):
        ax = axes[i]
        sub = df[df["Element"] == el][["n_star", "val_e1_l"]].dropna()
        for l_val in sorted(sub["val_e1_l"].unique()):
            lsub = sub[sub["val_e1_l"] == l_val]["n_star"]
            ax.hist(lsub, bins=15, color=L_COLORS[int(l_val) % len(L_COLORS)],
                    alpha=0.6, edgecolor="none", label=L_NAMES.get(int(l_val), str(int(l_val))))
        ax.set_title(f"{el}", fontsize=11)
        ax.set_xlabel("n* (effective quantum number)", fontsize=9)
        ax.set_ylabel("count", fontsize=9)
        ax.legend(title="l", fontsize=8, title_fontsize=8)
        ax.tick_params(labelsize=8)
    _suptitle(fig, "n* distribution per element and series")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def plot_permutation_importance(perm_df, baseline_mae, pdf):
    d = perm_df.sort_values("mean_mae_increase", ascending=True)
    fig, ax = plt.subplots(figsize=(10, max(6, len(d) * 0.35)))
    y = np.arange(len(d))
    ax.barh(y, d["mean_mae_increase"], xerr=d["std_mae_increase"],
            color="#378ADD", ecolor="black", capsize=3, height=0.7)
    ax.axvline(0, color="black", ls="--", lw=0.8)
    ax.set_yticks(y)
    ax.set_yticklabels(d["feature"], fontsize=9)
    ax.set_xlabel("Mean MAE increase (cm⁻¹)", fontsize=11)
    _suptitle(fig, f"Permutation feature importance  (baseline MAE = {baseline_mae:.1f} cm⁻¹)\n"
                   "MAE increase when each feature is shuffled — higher = more relied upon")
    fig.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Model-based: permutation importance (optional)
# ---------------------------------------------------------------------------

def run_permutation_importance(training_config_path, checkpoint_path):
    """
    Compute permutation importance for a trained MLP. Returns (DataFrame, baseline_mae)
    or (None, None) on any failure (missing torch, no checkpoint, etc.).
    """
    try:
        import torch
        from AtomicDataset import AtomicDataset
        from AtomicModel import create_model
        from utils import load_checkpoint, get_model_name_from_config, load_config
    except Exception as exc:
        print(f"  [permutation] skipped — could not import training stack: {exc}")
        return None, None

    try:
        config = load_config(training_config_path)
        device = torch.device("cuda" if (config.general.device == "cuda" and torch.cuda.is_available()) else "cpu")

        train_ds = AtomicDataset(config, subset="train")
        test_ds = AtomicDataset(config, subset="test",
                                scaler_features=train_ds.scaler_features,
                                scaler_target=train_ds.scaler_target)

        if checkpoint_path is None:
            checkpoint_path = os.path.join(config.logging.save_dir, get_model_name_from_config(config))
        if not os.path.exists(checkpoint_path):
            print(f"  [permutation] skipped — checkpoint not found: {checkpoint_path}")
            return None, None

        model = create_model(config, test_ds.get_input_dim()).to(device)
        optimizer = torch.optim.Adam(model.parameters())
        load_checkpoint(model, optimizer, checkpoint_path, device)
        model.eval()
        print(f"  [permutation] loaded model: {checkpoint_path}")

        X = test_ds.X.astype(np.float32)
        y = test_ds.inverse_transform_target(test_ds.y).flatten()
        feature_names = test_ds.get_feature_names()

        def predict(arr):
            with torch.no_grad():
                out = model(torch.FloatTensor(arr).to(device))
                # MultiTaskAtomicModel returns a (energy_pred, gj_pred) tuple;
                # single-task model returns a plain tensor.  Always take the
                # energy head (first element) so permutation importance measures
                # the effect on energy prediction regardless of model type.
                energy_out = out[0] if isinstance(out, tuple) else out
                raw = energy_out.cpu().numpy()
            return test_ds.inverse_transform_target(raw).flatten()

        baseline_mae = float(np.mean(np.abs(predict(X) - y)))
        rng = np.random.default_rng(42)
        records = []
        for i in range(len(feature_names)):
            inc = []
            for _ in range(30):
                Xp = X.copy()
                Xp[:, i] = rng.permutation(Xp[:, i])
                inc.append(float(np.mean(np.abs(predict(Xp) - y))) - baseline_mae)
            records.append({"feature": feature_names[i],
                            "mean_mae_increase": float(np.mean(inc)),
                            "std_mae_increase": float(np.std(inc))})
        out = (pd.DataFrame(records)
               .sort_values("mean_mae_increase", ascending=False)
               .reset_index(drop=True))
        out.insert(0, "rank", range(1, len(out) + 1))
        print(f"  [permutation] baseline MAE {baseline_mae:.2f} cm⁻¹, "
              f"{len(out)} features ranked")
        return out, baseline_mae
    except Exception as exc:
        print(f"  [permutation] skipped — {type(exc).__name__}: {exc}")
        return None, None


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------

def mi_results_to_wide(mi_results):
    wide = None
    for label, res in mi_results.items():
        s = res.set_index("feature")["mutual_information"].rename(label)
        wide = s.to_frame() if wide is None else wide.join(s, how="outer")
    return wide


def build_pdf(out_path, df, features, elements, targets, mi_results,
              perm, no_rydberg):
    perm_df, baseline_mae = perm
    print(f"  writing PDF → {out_path}")
    with PdfPages(out_path) as pdf:
        # Title page
        fig, ax = plt.subplots(figsize=(12, 6))
        ax.axis("off")
        ax.text(0.5, 0.66, "Feature Analysis Report", ha="center", va="center",
                fontsize=22, fontweight="bold", transform=ax.transAxes)
        ax.text(0.5, 0.52, f"Elements: {', '.join(elements)}    ·    n={len(df)} samples",
                ha="center", va="center", fontsize=14, transform=ax.transAxes, color="#5a5a5a")
        ax.text(0.5, 0.40, f"Features analysed: {', '.join(features)}",
                ha="center", va="center", fontsize=10, transform=ax.transAxes,
                color="#7a7a7a", wrap=True)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        plot_feature_distributions(df, features, elements, pdf)
        plot_correlation_matrix(df, features, targets, pdf)
        plot_mutual_information(mi_results, pdf)

        log_scatter = "log_binding_energy" if "log_binding_energy" in df.columns else LEVEL_COL
        plot_feature_target_scatter(df, features, log_scatter, elements, pdf)
        for col, _ in targets:
            if col != log_scatter:
                plot_feature_target_scatter(df, features, col, elements, pdf)

        if not no_rydberg:
            plot_rydberg_residuals(df, elements, pdf)
            plot_quantum_defect(df, elements, pdf)
        plot_feature_ranges(df, features, elements, pdf)
        if not no_rydberg:
            plot_nstar_distribution(df, elements, pdf)

        if perm_df is not None:
            plot_permutation_importance(perm_df, baseline_mae, pdf)


def build_xlsx(out_path, df, features, targets, mi_results, perm):
    perm_df, _ = perm
    print(f"  writing XLSX → {out_path}")
    mi_wide = mi_results_to_wide(mi_results)
    target_cols = [c for c, _ in targets]
    corr_cols = [c for c in features + target_cols if c in df.columns]
    corr = df[corr_cols].corr()
    summary = build_summary_table(df, features)
    samples = df.groupby("Element").size().rename("n_samples").to_frame()

    with pd.ExcelWriter(out_path, engine="openpyxl") as xl:
        if mi_wide is not None:
            mi_wide.to_excel(xl, sheet_name="mutual_information")
        corr.to_excel(xl, sheet_name="correlation")
        summary.to_excel(xl, sheet_name="summary_stats", index=False)
        samples.to_excel(xl, sheet_name="samples_per_element")
        if perm_df is not None:
            perm_df.to_excel(xl, sheet_name="permutation_importance", index=False)


_REPORT_CSS = """
:root { --navy:#0f172a; --navy2:#1e293b; --ink:#1f2937; --muted:#6b7280;
  --line:#e5e7eb; --bg:#f7f8fa; }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font-family:'IBM Plex Sans',-apple-system,Segoe UI,Roboto,sans-serif; line-height:1.55; }
code, .eqn, .mono { font-family:'IBM Plex Mono',ui-monospace,Menlo,monospace; }

/* Sidebar */
.sidebar { position:fixed; top:0; left:0; width:240px; height:100vh; background:var(--navy);
  color:#cbd5e1; padding:22px 0; overflow-y:auto; z-index:50; }
.sidebar .brand { font-size:20px; font-weight:700; color:#fff; padding:0 22px 16px;
  border-bottom:1px solid #1e293b; }
.sidebar .brand span { display:block; font-size:12px; font-weight:400; color:#64748b; margin-top:2px; }
.sidebar ul { list-style:none; margin:14px 0; padding:0; }
.sidebar li a { display:block; padding:9px 22px; color:#cbd5e1; text-decoration:none;
  font-size:14px; border-left:3px solid transparent; }
.sidebar li a:hover { background:#1e293b; color:#fff; border-left-color:#3b82f6; }
.nav-foot { padding:14px 22px; font-size:11px; color:#475569; border-top:1px solid #1e293b;
  position:absolute; bottom:0; width:100%; }
.menu-btn { display:none; position:fixed; top:12px; left:12px; z-index:60;
  background:var(--navy); color:#fff; border:0; border-radius:6px; padding:8px 12px; font-size:14px; }

/* Content */
.content { margin-left:240px; max-width:1080px; padding:0 40px 80px; }
.page-head { padding:40px 0 28px; border-bottom:2px solid var(--line); margin-bottom:8px; }
.page-head h1 { font-size:26px; margin:0 0 8px; color:var(--navy); }
.page-head p { margin:0; color:var(--muted); font-size:15px; }
section { padding:34px 0; border-bottom:1px solid var(--line); scroll-margin-top:20px; }
section > h2 { font-size:21px; color:var(--navy); margin:0 0 18px; }
section h3 { font-size:16px; color:var(--navy2); margin:26px 0 12px; }
section h4 { font-size:14px; margin:0 0 12px; }
.muted { color:var(--muted); font-weight:400; font-size:12px; }

/* Intro two-column */
.two-col { display:grid; grid-template-columns:1fr 280px; gap:30px; align-items:start; }
.col-text p { margin:0 0 14px; }
.glance { background:var(--navy); color:#fff; border-radius:12px; padding:22px; }
.glance h3 { color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:.08em;
  margin:0 0 14px; }
.g-num { font-size:24px; font-weight:700; color:#fff; }
.g-lbl { font-size:12px; color:#94a3b8; margin-bottom:16px; }

/* Dataset cards */
.card-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-bottom:24px; }
.dcard { background:#fff; border:1px solid var(--line); border-radius:10px; padding:16px 18px; }
.dc-t { font-size:12px; color:var(--muted); text-transform:uppercase; letter-spacing:.04em; }
.dc-v { font-size:20px; font-weight:600; color:var(--navy); margin:6px 0 4px; }
.dc-s { font-size:12px; color:var(--muted); }
.card { background:#fff; border:1px solid var(--line); border-radius:10px; padding:20px;
  margin-bottom:20px; }
.doughnut-wrap { max-width:420px; margin:0 auto; height:300px; }
.note, .desc { background:#eff6ff; border-left:4px solid #2563eb; border-radius:6px;
  padding:14px 18px; margin:16px 0; }
.note p, .desc p { margin:0 0 8px; font-size:14px; }
.note p:last-child, .desc p:last-child { margin-bottom:0; }

/* Feature catalogue */
.group { margin-bottom:30px; }
.group-head { border-left:5px solid; padding:6px 0 6px 14px; margin-bottom:14px; }
.group-head h3 { margin:0; color:var(--navy); }
.feat-cards { display:grid; grid-template-columns:1fr 1fr; gap:16px; }
.fcard { border:1px solid var(--line); border-top:3px solid var(--gc,#888); border-radius:10px;
  padding:16px 18px; background:#fff; }
.fc-name code { font-size:15px; font-weight:600; color:var(--navy); background:#f1f5f9;
  padding:2px 7px; border-radius:5px; }
.fc-disp { display:block; font-size:13px; color:var(--muted); margin-top:5px; }
.eqn { background:#0f172a; color:#e2e8f0; border-radius:6px; padding:10px 14px; margin:12px 0;
  font-size:14px; overflow-x:auto; }
.phys p { font-size:14px; margin:0 0 8px; }
.why { background:#eff6ff; border-radius:6px; padding:10px 14px; margin:10px 0; }
.why-tag { display:inline-block; font-size:11px; font-weight:600; color:#2563eb;
  text-transform:uppercase; letter-spacing:.05em; margin-bottom:4px; }
.why p { font-size:13px; margin:0; color:#1e3a5f; }
.ref { font-size:12px; font-style:italic; color:var(--muted); margin-top:8px; }

/* Tables */
.table-wrap { overflow-x:auto; }
table { border-collapse:collapse; width:100%; font-size:13px; }
th, td { border:1px solid var(--line); padding:7px 10px; text-align:right; }
th { background:#f1f5f9; color:var(--navy2); }
td:first-child, th:first-child { text-align:left; }
table.sortable th { cursor:pointer; user-select:none; }
table.sortable th:hover { background:#e2e8f0; }
tr.best { background:#ecfdf5; font-weight:600; }
.empty { color:var(--muted); font-style:italic; }

/* Heatmap */
.heatmap-wrap { overflow-x:auto; padding-top:60px; }
table.heatmap { border-collapse:collapse; width:auto; }
table.heatmap td, table.heatmap th { border:1px solid #fff; padding:0; width:34px; height:26px;
  text-align:center; font-size:10px; }
table.heatmap th.hrow { background:#f1f5f9; text-align:right; padding:0 6px; white-space:nowrap;
  font-size:11px; width:auto; }
table.heatmap th.hrot { background:transparent; height:60px; position:relative; }
table.heatmap th.hrot span { position:absolute; bottom:4px; left:50%; transform:translateX(-50%) rotate(-60deg);
  transform-origin:left bottom; white-space:nowrap; font-size:11px; font-weight:500; }

/* Charts */
.chart-box { position:relative; width:100%; }

/* Outlook */
ul.outlook { list-style:none; padding:0; margin:0; }
ul.outlook li { display:flex; gap:14px; align-items:flex-start; background:#fff;
  border:1px solid var(--line); border-radius:10px; padding:16px 18px; margin-bottom:14px; }
ul.outlook .bullet { color:#2563eb; font-size:22px; line-height:1; }

.page-foot { padding:26px 0 0; color:var(--muted); font-size:13px; }

@media (max-width:880px) {
  .sidebar { transform:translateX(-100%); transition:transform .2s; }
  body.nav-open .sidebar { transform:translateX(0); }
  .menu-btn { display:block; }
  .content { margin-left:0; padding:50px 18px 60px; }
  .two-col, .card-grid, .feat-cards { grid-template-columns:1fr; }
}
"""

_REPORT_JS = """
const D = REPORT_DATA;
const FONT = "'IBM Plex Sans', sans-serif";
Chart.defaults.font.family = FONT;

// Custom horizontal error-bar plugin (no external dependency).
const errBarsH = {
  id:'errBarsH',
  afterDatasetsDraw(chart){
    const errs = chart.$errors;
    if(!errs) return;
    const {ctx, scales:{x}} = chart;
    const meta = chart.getDatasetMeta(0);
    ctx.save(); ctx.strokeStyle='#334155'; ctx.lineWidth=1;
    meta.data.forEach((bar,i)=>{
      const v = chart.data.datasets[0].data[i], e = errs[i];
      if(e==null) return;
      const yC = bar.y, xp = x.getPixelForValue(v+e), xm = x.getPixelForValue(v-e);
      ctx.beginPath();
      ctx.moveTo(xm,yC); ctx.lineTo(xp,yC);
      ctx.moveTo(xm,yC-4); ctx.lineTo(xm,yC+4);
      ctx.moveTo(xp,yC-4); ctx.lineTo(xp,yC+4);
      ctx.stroke();
    });
    ctx.restore();
  }
};

// Mutual information charts
(D.mi||[]).forEach((m,i)=>{
  const el = document.getElementById('mi_chart_'+i);
  if(!el) return;
  new Chart(el, {
    type:'bar',
    data:{ labels:m.labels, datasets:[{ data:m.values, backgroundColor:m.colors }] },
    options:{ indexAxis:'y', responsive:true, maintainAspectRatio:false,
      plugins:{ legend:{display:false},
        tooltip:{callbacks:{label:c=>'MI: '+c.parsed.x.toFixed(4)}} },
      scales:{ x:{ beginAtZero:true, title:{display:true,text:'Mutual information'} },
               y:{ ticks:{ font:{size:11} } } } }
  });
});

// Permutation importance with error bars
if(D.perm){
  const el = document.getElementById('permChart');
  if(el){
    const ch = new Chart(el, {
      type:'bar',
      data:{ labels:D.perm.labels, datasets:[{ data:D.perm.values, backgroundColor:D.perm.colors }] },
      options:{ indexAxis:'y', responsive:true, maintainAspectRatio:false,
        plugins:{ legend:{display:false},
          tooltip:{callbacks:{label:c=>'ΔMAE: '+c.parsed.x.toFixed(2)+' cm⁻¹'}} },
        scales:{ x:{ title:{display:true,text:'Mean MAE increase (cm⁻¹)'} },
                 y:{ ticks:{ font:{size:11} } } } },
      plugins:[errBarsH]
    });
    ch.$errors = D.perm.errors;
    ch.update();
  }
}

// Configuration complexity doughnut
(function(){
  const el = document.getElementById('complexityChart');
  if(!el || !D.complexity || !D.complexity.values.length) return;
  const palette = ['#2563eb','#16a34a','#9333ea','#dc2626','#BA7517','#0EA5E9'];
  new Chart(el, {
    type:'doughnut',
    data:{ labels:D.complexity.labels,
      datasets:[{ data:D.complexity.values,
        backgroundColor:D.complexity.labels.map((_,i)=>palette[i%palette.length]) }] },
    options:{ responsive:true, maintainAspectRatio:false,
      plugins:{ legend:{position:'right'},
        tooltip:{callbacks:{label:c=>c.label+': '+c.parsed+' levels'}} } }
  });
})();

// Predicted vs observed scatter
(function(){
  const el = document.getElementById('scatterChart');
  if(!el || !D.scatter) return;
  const ds = D.scatter.datasets.map(s=>({
    type:'scatter', label:s.label, data:s.points,
    backgroundColor:s.color, pointRadius:3, pointHoverRadius:5 }));
  const d = D.scatter.diag;
  ds.push({ type:'line', label:'perfect prediction',
    data:[{x:d.min,y:d.min},{x:d.max,y:d.max}],
    borderColor:'#64748b', borderDash:[6,5], borderWidth:1.5,
    pointRadius:0, fill:false });
  new Chart(el, {
    data:{ datasets:ds },
    options:{ responsive:true, maintainAspectRatio:false,
      plugins:{ legend:{position:'top'} },
      scales:{ x:{ title:{display:true,text:'Observed energy (cm⁻¹)'} },
               y:{ title:{display:true,text:'Predicted energy (cm⁻¹)'} } } }
  });
})();

// Click-to-sort tables
function sortTable(id, th){
  const table = document.getElementById(id);
  const tbody = table.tBodies[0];
  const idx = Array.from(th.parentNode.children).indexOf(th);
  const asc = !(th.dataset.asc === 'true');
  th.dataset.asc = asc;
  const rows = Array.from(tbody.rows);
  rows.sort((a,b)=>{
    let x = a.cells[idx].dataset.v, y = b.cells[idx].dataset.v;
    const nx = parseFloat(x), ny = parseFloat(y);
    if(!isNaN(nx) && !isNaN(ny)){ return asc ? nx-ny : ny-nx; }
    return asc ? String(x).localeCompare(y) : String(y).localeCompare(x);
  });
  rows.forEach(r=>tbody.appendChild(r));
}
"""


def _latex_to_html(eq):
    """
    Render the small subset of LaTeX used in report_content.yaml equations as
    inline HTML with Unicode symbols and <sub>/<sup> tags — no MathJax needed.
    """
    import re
    s = eq or ""
    s = re.sub(r"\\text\{([^}]*)\}", r"\1", s)
    s = re.sub(r"\\mathbf\{([^}]*)\}", r"<b>\1</b>", s)
    # Protect escaped literals so the sub/sup passes below leave them alone.
    s = s.replace("\\_", "\x01").replace("\\{", "\x02").replace("\\}", "\x03")
    for pat, sym in [
        (r"\\zeta", "ζ"), (r"\\sigma", "σ"), (r"\\times", "×"),
        (r"\\approx", "≈"), (r"\\in", "∈"), (r"\\sum", "Σ"),
        (r"\\ell", "ℓ"), (r"\\bmod", " mod "), (r"\\quad", "&nbsp;&nbsp;&nbsp;&nbsp;"),
        (r"\\,", " "), (r"\\;", " "), (r"\\cdot", "·"),
        (r"\\left", ""), (r"\\right", ""), (r"\\Delta", "Δ"), (r"\\delta", "δ"),
    ]:
        s = re.sub(pat, sym, s)
    s = re.sub(r"_\{([^}]*)\}", r"<sub>\1</sub>", s)
    s = re.sub(r"\^\{([^}]*)\}", r"<sup>\1</sup>", s)
    s = re.sub(r"_([A-Za-z0-9])", r"<sub>\1</sub>", s)
    s = re.sub(r"\^([A-Za-z0-9])", r"<sup>\1</sup>", s)
    return s.replace("\x01", "_").replace("\x02", "{").replace("\x03", "}")


def _esc(text):
    """Minimal HTML escaping for plain text content."""
    return (str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _paras(text):
    """Split a YAML block scalar on blank lines into <p> paragraphs."""
    import re
    out = []
    for chunk in re.split(r"\n\s*\n", (text or "").strip()):
        chunk = " ".join(chunk.split())
        if chunk:
            out.append(f"<p>{_esc(chunk)}</p>")
    return "".join(out)


def _oneline(text):
    """Collapse a YAML block scalar to a single escaped line."""
    return _esc(" ".join((text or "").split()))


def _corr_color(r):
    """Interpolate a Pearson r in [-1, 1] from blue (#2563eb) through white to red (#dc2626)."""
    if r != r:           # NaN
        return "#f9fafb"
    if r >= 0:
        t = min(r, 1.0)
        (r1, g1, b1), (r2, g2, b2) = (255, 255, 255), (220, 38, 38)
    else:
        t = min(-r, 1.0)
        (r1, g1, b1), (r2, g2, b2) = (255, 255, 255), (37, 99, 235)
    return "rgb(%d,%d,%d)" % (int(r1 + (r2 - r1) * t),
                              int(g1 + (g2 - g1) * t),
                              int(b1 + (b2 - b1) * t))


def build_html(out_path, df, features, elements, modes, targets, mi_results, perm,
               preprocessing_info=None, predictions_df=None, results_df=None):
    """
    Render a single self-contained physicist-facing HTML report.

    All fixed text and physics definitions come from report_content.yaml (no
    physics is hardcoded here). Optional inputs (preprocessing_info,
    predictions_df, results_df) enrich the dataset/results sections when present
    and degrade gracefully when absent. All data is embedded as inline JSON, so
    the report needs no data files at view time (only the Chart.js CDN).
    """
    import yaml
    perm_df, baseline_mae = perm
    print(f"  writing HTML → {out_path}")

    content_file = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "report_content.yaml")
    with open(content_file, "r", encoding="utf-8") as f:
        content = yaml.safe_load(f)

    rep = content.get("report", {})
    groups = content.get("feature_groups", [])
    descs = content.get("chart_descriptions", {})
    pinfo = preprocessing_info or {}

    # Map each catalogued feature column -> its group colour (split "a / b" names).
    feat_color = {}
    import re as _re
    for g in groups:
        for feat in g.get("features", []):
            for nm in _re.split(r"\s*/\s*", feat.get("name", "")):
                if nm.strip():
                    feat_color[nm.strip()] = g.get("color", "#888780")

    def pget(key, default=None):
        return pinfo[key] if key in pinfo else default

    # ---- Data prep --------------------------------------------------------
    feat_present = [f for f in features if f in df.columns]

    # Dataset overview numbers (preprocessing_info preferred, else derive from df).
    total_levels = pget("total_rows", len(df))
    rows_obs_gj = pget("rows_with_obs_gj")
    pct_obs_gj = pget("pct_obs_gj")
    rows_term = pget("rows_term_known")
    if rows_term is None and "term_known" in df.columns:
        rows_term = int(pd.to_numeric(df["term_known"], errors="coerce").fillna(0).sum())
    n_even = pget("n_even")
    n_odd = pget("n_odd")
    if (n_even is None or n_odd is None) and "parity_computed" in df.columns:
        vc = pd.to_numeric(df["parity_computed"], errors="coerce").value_counts()
        n_even = int(vc.get(0, 0))
        n_odd = int(vc.get(1, 0))
    e_min = pget("energy_min")
    e_max = pget("energy_max")
    if (e_min is None or e_max is None) and LEVEL_COL in df.columns:
        e_min = float(df[LEVEL_COL].min())
        e_max = float(df[LEVEL_COL].max())
    top_terms = pget("top_comp1_terms")

    # Configuration-complexity doughnut (n_components distribution).
    comp_counts = pget("n_components")
    if comp_counts is None and "n_components" in df.columns:
        vc = pd.to_numeric(df["n_components"], errors="coerce").dropna().astype(int).value_counts()
        comp_counts = {int(k): int(v) for k, v in vc.items()}
    comp_counts = comp_counts or {}
    comp_labels = [f"{k}-component" for k in sorted(comp_counts)]
    comp_values = [comp_counts[k] for k in sorted(comp_counts)]

    # Mutual information charts (one per target).
    mi_payload = []
    for label, res in mi_results.items():
        vals = [round(float(v), 4) for v in res["mutual_information"]]
        med = float(np.median(res["mutual_information"])) if len(vals) else 0.0
        colors = ["#1D9E75" if v > med else "#888780" for v in vals]
        mi_payload.append({
            "target": label,
            "labels": res["feature"].tolist(),
            "values": vals,
            "colors": colors,
            "median": round(med, 4),
        })

    # Permutation importance chart, coloured by feature group.
    perm_payload = None
    if perm_df is not None:
        d = perm_df.sort_values("mean_mae_increase", ascending=True)
        perm_payload = {
            "labels": d["feature"].tolist(),
            "values": [round(float(v), 3) for v in d["mean_mae_increase"]],
            "errors": [round(float(v), 3) for v in d["std_mae_increase"]],
            "colors": [feat_color.get(f, "#888780") for f in d["feature"]],
            "baseline": round(float(baseline_mae), 1) if baseline_mae is not None else None,
        }

    # Predicted-vs-observed scatter.
    scatter_payload = None
    if predictions_df is not None and "True_Energy_cm-1" in predictions_df.columns:
        pred_cols = [c for c in predictions_df.columns if c.startswith("Predicted_")]
        nice = {
            "Predicted_raw_no-weights": "Raw energy",
            "Predicted_binded_no-weights": "Binding energy",
            "Predicted_log-binded_no-weights": "Log-binding",
            "Predicted_inv-binded_no-weights": "Inverse-binding",
        }
        palette = ["#2563eb", "#16a34a", "#dc2626", "#9333ea", "#BA7517", "#0EA5E9"]
        x = pd.to_numeric(predictions_df["True_Energy_cm-1"], errors="coerce")
        datasets = []
        for i, col in enumerate(pred_cols):
            y = pd.to_numeric(predictions_df[col], errors="coerce")
            pts = [{"x": round(float(xv), 2), "y": round(float(yv), 2)}
                   for xv, yv in zip(x, y) if pd.notna(xv) and pd.notna(yv)]
            datasets.append({
                "label": nice.get(col, col.replace("Predicted_", "")),
                "color": palette[i % len(palette)],
                "points": pts,
            })
        lo = float(x.min())
        hi = float(x.max())
        scatter_payload = {"datasets": datasets, "diag": {"min": round(lo, 2), "max": round(hi, 2)}}

    report_data = {
        "mi": mi_payload,
        "perm": perm_payload,
        "complexity": {"labels": comp_labels, "values": comp_values},
        "scatter": scatter_payload,
    }

    # ---- HTML assembly ----------------------------------------------------
    P = []
    a = P.append
    nfeat = len(feat_present)

    def fmt_int(v):
        return "—" if v is None else f"{int(v):,}"

    # § Sidebar ------------------------------------------------------------
    nav_items = [
        ("intro", "1 · Introduction"),
        ("dataset", "2 · Dataset Overview"),
        ("catalogue", "3 · Feature Catalogue"),
        ("stats", "4 · Feature Statistics"),
        ("collinearity", "5 · Collinearity"),
        ("importance", "6 · Feature Importance"),
        ("results", "7 · Model Results"),
        ("outlook", "8 · Outlook"),
    ]

    a("<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>")
    a("<meta name='viewport' content='width=device-width, initial-scale=1'>")
    a(f"<title>{_esc(rep.get('title', 'Feature Analysis'))}</title>")
    a("<link rel='preconnect' href='https://fonts.googleapis.com'>")
    a("<link href='https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&"
      "family=IBM+Plex+Mono:wght@400;500&display=swap' rel='stylesheet'>")
    a("<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js'></script>")
    a("<style>" + _REPORT_CSS + "</style></head><body>")

    # Sidebar
    a("<nav class='sidebar'>")
    a(f"<div class='brand'>Co I<span>feature report</span></div>")
    a("<ul>")
    for sid, lbl in nav_items:
        a(f"<li><a href='#{sid}'>{_esc(lbl)}</a></li>")
    a("</ul>")
    a("<div class='nav-foot'>Generated " + _dt.date.today().isoformat() + "</div>")
    a("</nav>")
    a("<button class='menu-btn' onclick=\"document.body.classList.toggle('nav-open')\">☰ Sections</button>")

    a("<main class='content'>")

    # § Header
    a("<header class='page-head'>")
    a(f"<h1>{_esc(rep.get('title', ''))}</h1>")
    a(f"<p>{_esc(rep.get('subtitle', ''))}</p>")
    a("</header>")

    # §1 Introduction
    a("<section id='intro'><h2>1 · Introduction</h2>")
    a("<div class='two-col'>")
    a("<div class='col-text'>" + _paras(rep.get("introduction", "")) + "</div>")
    a("<aside class='glance'><h3>At a glance</h3>")
    a(f"<div class='g-num'>{fmt_int(total_levels)}</div><div class='g-lbl'>energy levels</div>")
    a(f"<div class='g-num'>{nfeat}</div><div class='g-lbl'>engineered features</div>")
    a("<div class='g-num'>~1 cm⁻¹</div><div class='g-lbl'>target accuracy</div>")
    a(f"<div class='g-num'>{_esc(', '.join(elements))}</div><div class='g-lbl'>element(s) · Kurucz</div>")
    a("</aside></div></section>")

    # §2 Dataset Overview
    a("<section id='dataset'><h2>2 · Dataset Overview</h2>")
    gj_txt = "—"
    if rows_obs_gj is not None:
        gj_txt = fmt_int(rows_obs_gj) + (f" ({pct_obs_gj:.1f}%)" if pct_obs_gj is not None else "")
    erange = "—"
    if e_min is not None and e_max is not None:
        erange = f"{e_min:,.0f} – {e_max:,.0f}"
    if top_terms:
        top_txt = ", ".join(f"{t}&nbsp;({n})" for t, n in top_terms[:5])
    else:
        top_txt = "see Feature Catalogue (§3)"
    cells = [
        ("Total levels", fmt_int(total_levels), "rows in the Co I dataset"),
        ("With observed g<sub>J</sub>", gj_txt, "Landé g-factor measured"),
        ("Term known", fmt_int(rows_term), "confirmed LS term assignment"),
        ("Parity split", f"{fmt_int(n_even)} even / {fmt_int(n_odd)} odd", "even vs odd configurations"),
        ("Energy range", erange + " cm⁻¹", "lowest to highest level"),
        ("Top 3d sub-terms", top_txt, "most frequent comp1 terms"),
    ]
    a("<div class='card-grid'>")
    for title, val, sub in cells:
        a(f"<div class='dcard'><div class='dc-t'>{title}</div>"
          f"<div class='dc-v'>{val}</div><div class='dc-s'>{_esc(sub)}</div></div>")
    a("</div>")
    a("<div class='card'><h3>Configuration complexity</h3>"
      "<div class='doughnut-wrap'><canvas id='complexityChart'></canvas></div></div>")
    a("<div class='note'>" + _paras(rep.get("dataset_note", "")) + "</div>")
    a("</section>")

    # §3 Feature Catalogue
    a("<section id='catalogue'><h2>3 · Feature Catalogue</h2>")
    for g in groups:
        color = g.get("color", "#888780")
        a(f"<div class='group' style='--gc:{color}'>")
        a(f"<div class='group-head' style='border-left-color:{color}'>"
          f"<h3>{_esc(g.get('name', ''))}</h3></div>")
        a("<div class='feat-cards'>")
        for feat in g.get("features", []):
            a("<div class='fcard'>")
            a(f"<div class='fc-name'><code>{_esc(feat.get('name', ''))}</code>"
              f"<span class='fc-disp'>{_esc(feat.get('display', ''))}</span></div>")
            a(f"<div class='eqn'>{_latex_to_html(feat.get('equation', ''))}</div>")
            a(f"<div class='phys'>{_paras(feat.get('physical_meaning', ''))}</div>")
            a("<div class='why'><span class='why-tag'>Why this feature?</span>"
              + _paras(feat.get("ml_rationale", "")) + "</div>")
            a(f"<div class='ref'>{_esc(feat.get('reference', ''))}</div>")
            a("</div>")
        a("</div></div>")
    a("</section>")

    # §4 Feature Statistics
    a("<section id='stats'><h2>4 · Feature Statistics</h2>")
    a("<div class='desc'>" + _paras(descs.get("feature_statistics", "")) + "</div>")
    summ = build_summary_table(df, feat_present)
    a("<div class='table-wrap'><table class='sortable' id='statsTable'><thead><tr>")
    for col in summ.columns:
        a(f"<th onclick='sortTable(\"statsTable\", this)'>{_esc(col)}</th>")
    a("</tr></thead><tbody>")
    for _, row in summ.iterrows():
        a("<tr>")
        for col in summ.columns:
            v = row[col]
            cell = _esc(v) if col == "feature" else (f"{v:.4g}" if isinstance(v, (int, float, np.floating)) else _esc(v))
            a(f"<td data-v='{_esc(v)}'>{cell}</td>")
        a("</tr>")
    a("</tbody></table></div></section>")

    # §5 Collinearity
    a("<section id='collinearity'><h2>5 · Collinearity Analysis</h2>")
    a("<div class='desc'>" + _paras(descs.get("correlation_matrix", "")) + "</div>")
    corr = df[feat_present].corr()
    n = len(feat_present)
    short = [c[:12] for c in feat_present]
    a("<div class='heatmap-wrap'><table class='heatmap'><thead><tr><th></th>")
    for s in short:
        a(f"<th class='hrot'><span>{_esc(s)}</span></th>")
    a("</tr></thead><tbody>")
    for i in range(n):
        a(f"<tr><th class='hrow'>{_esc(short[i])}</th>")
        for j in range(n):
            if j > i:
                a("<td style='background:#f9fafb'></td>")
            else:
                r = corr.values[i, j]
                txt = "" if r != r else f"{r:.2f}"
                fg = "#fff" if (r == r and abs(r) > 0.6) else "#111"
                a(f"<td style='background:{_corr_color(r)};color:{fg}'>{txt}</td>")
        a("</tr>")
    a("</tbody></table></div>")

    # Flagged pairs |r| > 0.95
    flagged = []
    for i in range(n):
        for j in range(i):
            r = corr.values[i, j]
            if r == r and abs(r) > 0.95:
                fa, fb = feat_present[i], feat_present[j]
                const = (df[fa].nunique() <= 2) or (df[fb].nunique() <= 2)
                note = ("May resolve with multi-element training" if const
                        else "Redundant within Co I — consider pruning")
                flagged.append((fa, fb, r, note))
    a("<h3>Flagged pairs (|r| &gt; 0.95)</h3>")
    if flagged:
        a("<div class='table-wrap'><table><thead><tr><th>Feature A</th><th>Feature B</th>"
          "<th>r</th><th>Note</th></tr></thead><tbody>")
        for fa, fb, r, note in flagged:
            a(f"<tr><td>{_esc(fa)}</td><td>{_esc(fb)}</td><td>{r:.3f}</td>"
              f"<td style='text-align:left'>{_esc(note)}</td></tr>")
        a("</tbody></table></div>")
    else:
        a("<p class='empty'>No feature pairs exceed |r| = 0.95.</p>")
    a("</section>")

    # §6 Feature Importance
    a("<section id='importance'><h2>6 · Feature Importance</h2>")
    a("<h3>6a · Mutual Information</h3>")
    a("<div class='desc'>" + _paras(descs.get("mutual_information", "")) + "</div>")
    for i, m in enumerate(mi_payload):
        h = max(400, 20 * len(m["labels"]))
        a(f"<div class='card'><h4>Target: <code>{_esc(m['target'])}</code></h4>"
          f"<div class='chart-box' style='height:{h}px'><canvas id='mi_chart_{i}'></canvas></div></div>")
    if not mi_payload:
        a("<p class='empty'>No mutual-information results available.</p>")

    a("<h3>6b · Permutation Importance</h3>")
    a("<div class='desc'>" + _paras(descs.get("permutation_importance", "")) + "</div>")
    if perm_payload is not None:
        h = max(400, 20 * len(perm_payload["labels"]))
        sub = (f"baseline MAE = {perm_payload['baseline']} cm⁻¹"
               if perm_payload["baseline"] is not None else "")
        a(f"<div class='card'><h4>Permutation importance <span class='muted'>{sub}</span></h4>"
          f"<div class='chart-box' style='height:{h}px'><canvas id='permChart'></canvas></div></div>")
    else:
        a("<p class='empty'>Permutation importance not available "
          "(no trained checkpoint supplied).</p>")
    a("</section>")

    # §7 Model Results
    a("<section id='results'><h2>7 · Model Results</h2>")
    a("<h3>7a · Results table</h3>")
    a("<div class='desc'>" + _paras(descs.get("model_results", "")) + "</div>")
    if results_df is not None and len(results_df):
        cols = [("experiment_tag", "Experiment"), ("target_feature", "Target"),
                ("test_mae", "MAE"), ("test_r2", "R²"),
                ("test_max_error", "Max error"), ("val_mae_gj", "g_J MAE")]
        cols = [(c, lbl) for c, lbl in cols if c in results_df.columns]
        best_idx = results_df["test_mae"].astype(float).idxmin() if "test_mae" in results_df.columns else None
        a("<div class='table-wrap'><table><thead><tr>")
        for _, lbl in cols:
            a(f"<th>{_esc(lbl)}</th>")
        a("</tr></thead><tbody>")
        for idx, row in results_df.iterrows():
            cls = " class='best'" if idx == best_idx else ""
            a(f"<tr{cls}>")
            for c, _ in cols:
                v = row[c]
                if c == "test_mae":
                    cell = f"{float(v):.1f} cm⁻¹"
                elif c == "test_r2":
                    cell = f"{float(v):.4f}"
                elif c == "test_max_error":
                    cell = f"{float(v):.0f} cm⁻¹"
                elif c == "val_mae_gj":
                    cell = "—" if pd.isna(v) else f"{float(v):.3f}"
                else:
                    cell = _esc(v)
                a(f"<td>{cell}</td>")
            a("</tr>")
        a("</tbody></table></div>")
    else:
        a("<p class='empty'>No model results file found.</p>")

    a("<h3>7b · Predicted vs Observed</h3>")
    a("<div class='desc'>" + _paras(descs.get("predicted_vs_observed", "")) + "</div>")
    if scatter_payload is not None:
        a("<div class='card'><div class='chart-box' style='height:560px'>"
          "<canvas id='scatterChart'></canvas></div></div>")
    else:
        a("<p class='empty'>No predictions file found.</p>")
    a("</section>")

    # §8 Outlook
    a("<section id='outlook'><h2>8 · Outlook</h2>")
    a("<ul class='outlook'>")
    for chunk in _re.split(r"\n\s*\n", (rep.get("outlook", "") or "").strip()):
        chunk = " ".join(chunk.split())
        if chunk:
            a(f"<li><span class='bullet'>▸</span><span>{_esc(chunk)}</span></li>")
    a("</ul></section>")

    # Footer
    base_mae = (f"{baseline_mae:.1f} cm⁻¹" if baseline_mae is not None else "n/a")
    a("<footer class='page-foot'>")
    a(f"Generated {_dt.date.today().isoformat()} · "
      f"element(s): {_esc(', '.join(elements))} · "
      f"n = {len(df)} samples · baseline MAE: {base_mae}")
    a("</footer>")

    a("</main>")

    # Inline data + chart rendering JS
    a("<script>const REPORT_DATA = " + json.dumps(report_data) + ";</script>")
    a("<script>" + _REPORT_JS + "</script>")
    a("</body></html>")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(P))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    settings, element_info = load_preprocess_config(args.config)

    source = (args.source or settings["source"]).lower()
    data_dir = args.data_dir or settings["data_dir"]
    report_dir = settings["report_dir"]
    elements = args.elements or list(element_info.keys())
    formats = [f.strip().lower() for f in args.formats.split(",") if f.strip()]

    ensure_element_colors(elements)

    print(f"Analysing elements: {elements}  (source preference: {source})")
    df, modes = load_elements(elements, data_dir, source, element_info)
    print(f"Combined: {len(df)} samples;  modes={modes}")

    features = select_features(df, modes, element_info)
    targets = get_targets(df)
    print(f"Features ({len(features)}): {features}")
    print(f"Targets: {[lbl for _, lbl in targets]}")

    mi_results = compute_mi_table(df, features, targets)

    # Optional model-based permutation importance.
    perm = (None, None)
    if not args.no_permutation and (args.checkpoint or any(m == "rich" for m in modes.values())):
        print("Permutation importance:")
        perm = run_permutation_importance(args.training_config, args.checkpoint)

    # Output base path.
    if args.out:
        base = args.out
    else:
        os.makedirs(report_dir, exist_ok=True)
        base = os.path.join(report_dir, f"features_{'_'.join(elements)}_{source}")
    out_dir = os.path.dirname(base)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    no_rydberg = args.no_rydberg or ("n_star" not in df.columns) or df["n_star"].dropna().empty

    # Optional inputs for the HTML report: model predictions and results metrics.
    # Looked up next to the base path first, then in the results/ dir by convention.
    predictions_df = results_df = None
    base_dir = os.path.dirname(base) or "."
    el_src = f"{'_'.join(elements)}_{source}"
    pred_candidates = [
        base + ".xlsx",
        os.path.join(base_dir, f"predictions_{el_src}.xlsx"),
        os.path.join(_ROOT, "results", f"predictions_{el_src}.xlsx"),
    ]
    res_candidates = [
        os.path.join(base_dir, f"results_{el_src}.xlsx"),
        os.path.join(_ROOT, "results", f"results_{el_src}.xlsx"),
    ]
    for p in pred_candidates:
        if os.path.exists(p):
            try:
                predictions_df = pd.read_excel(p, sheet_name="predictions")
                print(f"  loaded predictions: {p}")
                break
            except Exception as exc:
                print(f"  ⚠ could not read predictions '{p}': {type(exc).__name__}: {exc}")
    for p in res_candidates:
        if os.path.exists(p):
            try:
                results_df = pd.read_excel(p, sheet_name="metrics")
                print(f"  loaded results: {p}")
                break
            except Exception as exc:
                print(f"  ⚠ could not read results '{p}': {type(exc).__name__}: {exc}")

    # Populated manually or from a future preprocessing-log parser; None is fine
    # (the HTML report derives what it can from the dataframe).
    preprocessing_info = None

    print("Writing reports:")
    if "pdf" in formats:
        build_pdf(base + ".pdf", df, features, elements, targets, mi_results, perm, no_rydberg)
    if "xlsx" in formats:
        build_xlsx(base + ".xlsx", df, features, targets, mi_results, perm)
    if "html" in formats:
        build_html(base + ".html", df, features, elements, modes, targets, mi_results, perm,
                   preprocessing_info=preprocessing_info,
                   predictions_df=predictions_df, results_df=results_df)

    print(f"\nDone. Report base: {base}  formats={formats}")


if __name__ == "__main__":
    main()
